-- Cypress on-device seed schema.
--
-- Generated by Tools/build_seed.py. This file is the CONTRACT between the
-- ingest tooling and the app's GRDB layer: field names track BUILD-PLAN.md
-- section 4 as closely as SQLite allows. Deviations from section 4, all forced
-- by the absence of PostGIS on device or by on-device size limits, are called
-- out inline.
--
-- Timestamps are ISO-8601 UTC strings. Booleans are 0/1 INTEGERs. jsonb columns
-- from section 4 are TEXT holding JSON.
--
-- IDENTITY MODEL. Section 4 says "every table gets id uuid primary key". On
-- device that costs roughly 90 MB across the row payloads and every index that
-- copies a key, so the seed splits identity in two:
--
--   id    INTEGER PRIMARY KEY  -- internal join key, used by every FK, index
--                                and the R*Tree. Not stable across a rebuild;
--                                never expose it, never persist it off-device.
--   uuid  TEXT NOT NULL UNIQUE -- stable citable external identity, on the
--                                tables that need one (trees, species).
--                                DETERMINISTIC: a rebuild from the same TreeID
--                                reproduces the same uuid byte for byte, so
--                                public tree URLs and export rows survive a
--                                re-import. Required by DECISIONS.md
--                                constraint 13.
--
-- Frozen UUIDv5 namespace constants (see Tools/build_seed.py):
--   trees.uuid   = uuidv5(6f2a1d8e-0f3d-5d3e-9a1a-7c1f0b9a0001, <DataSF TreeID>)
--   species.uuid = uuidv5(6f2a1d8e-0f3d-5d3e-9a1a-7c1f0b9a0002, <scientific name,
--                         lowercased, whitespace-collapsed>)
-- Changing either constant rewrites every public identifier. Do not.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------- species --
-- The city import supplies only the two names. Every other content column
-- (family, leaf_retention, id_tips, seasonal, care_notes, curated) is filled
-- from Fixtures/species/*.yaml, the authored species pipeline of BUILD-PLAN
-- section 8, and is NULL or empty wherever no source could be found.
--
-- leaf_retention in particular is null for the species whose habit no
-- authoritative source states. That is a real state, not a gap to be papered
-- over with a default: unknown renders no phenology chip and no autumn colour
-- anywhere in the app (ERRATA E9).
CREATE TABLE species (
    id              INTEGER PRIMARY KEY,
    uuid            TEXT NOT NULL UNIQUE,       -- stable external identity
    scientific_name TEXT NOT NULL,
    common_name     TEXT,
    family          TEXT,

    -- Drives phenology chips and the season strip (D5).
    leaf_retention  TEXT
        CHECK (leaf_retention IS NULL
               OR leaf_retention IN ('evergreen','deciduous','semi_deciduous')),

    -- json array of {icon, text}; 2 to 4 entries once authored
    id_tips         TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(id_tips)),
    -- json {bloom_months:[], fall_color_months:[], fruit_months:[], new_growth_months:[]}
    seasonal        TEXT NOT NULL DEFAULT '{}' CHECK (json_valid(seasonal)),
    -- json array of {month_range, text}
    care_notes      TEXT NOT NULL DEFAULT '[]' CHECK (json_valid(care_notes)),

    curated         INTEGER NOT NULL DEFAULT 0 CHECK (curated IN (0,1)),
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    deleted_at      TEXT,

    -- D5 enforced in the database: an evergreen must never carry fall colour
    -- months, so the UI cannot render a fall-colour chip on an evergreen even
    -- if the content pipeline gets it wrong. `IS NOT` is the null-safe form, so
    -- a NULL leaf_retention (the unpopulated state) is unconstrained.
    CHECK (leaf_retention IS NOT 'evergreen'
           OR json_array_length(
                COALESCE(json_extract(seasonal, '$.fall_color_months'), '[]')) = 0)
);
CREATE UNIQUE INDEX idx_species_scientific_name ON species(scientific_name);
CREATE INDEX idx_species_common_name ON species(common_name);
CREATE INDEX idx_species_curated ON species(curated);

-- ---------------------------------------------------------- neighborhoods --
-- Section 4 stores geom as MultiPolygon. On device we keep the source GeoJSON
-- geometry verbatim in `geom_geojson` and precompute a bbox for cheap filters.
-- `name` is the stable external key here; no uuid column is needed.
CREATE TABLE neighborhoods (
    id           INTEGER PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    geom_geojson TEXT NOT NULL,
    min_lat      REAL NOT NULL,
    max_lat      REAL NOT NULL,
    min_lon      REAL NOT NULL,
    max_lon      REAL NOT NULL,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL
);

-- ------------------------------------------------------------------ trees --
-- Deviations from section 4:
--   geom geometry(Point,4326)   -> lat REAL + lon REAL (WGS84 degrees)
--   dbh_city_cm_range int4range -> dbh_city_cm_min / dbh_city_cm_max (half-open
--                                  [min, max), 5 cm buckets, both NULL together)
--   city_raw jsonb              -> city_raw TEXT holding a JSON object. NULL in
--                                  the shipped seed: the passthrough costs
--                                  ~74 MB and is regenerable from the raw CSV
--                                  via `build_seed.py --with-city-raw`. The
--                                  column is always declared so the schema
--                                  contract does not move.
--   external_ref text           -> INTEGER. Every DataSF TreeID observed is
--                                  numeric (verified across all 195,309 rows).
--
-- THE SIX CITY COLUMNS CARRY NO CHECK, AND THAT IS THE DECISION.
-- Every closed vocabulary in the *app* schema carries its vocabulary in a CHECK,
-- because that database is written by a DAO and by whoever opens it in a
-- debugger, and the invariant has to hold against both. None of that reasoning
-- reaches here. This file is a read-only bundle regenerated from a live city
-- feed; the only writer is the loop below, and the only "hand-written INSERT" a
-- CHECK could catch is one nobody can perform against a database shipped inside
-- an .app.
--
-- What a CHECK would do instead is pin twelve strings that belong to San
-- Francisco rather than to Cypress. qLegalStatus has 12 values this week and had
-- fewer before; qCaretaker has 27, and they read like an org chart -- 'Asian
-- Arts Commission', 'Mission Verde', 'Office of Mayor' -- which is a list that
-- grows whenever a department is renamed. A CHECK over it would turn the next
-- weekly diff into a build failure over a string the city was entitled to add.
-- That is ERRATA E136's mistake written in advance rather than discovered
-- afterwards: a constraint wearing a ruling's clothes, forbidding a state the
-- source is allowed to reach. BUILD-PLAN section 7 already settled the same
-- question the same way for site_type ("kept as free text because the source
-- vocabulary is open-ended"), and these six are the same kind of column.
--
-- The vocabulary that IS closed -- street / city park / private property /
-- other public land -- is Cypress's own, is derived from these columns rather
-- than stored beside them, and is CHECK-pinned where it is actually written
-- down: main.community_trees.land_context (AppSchema v11). The derivation lives
-- in LandContext.inferred(from:) so that changing our reading of the city's
-- vocabulary is a code change rather than a 95 MB rebuild.
--
-- plot_size is TEXT and is never parsed into a number. The city's own 588
-- distinct values include 'Width 3ft', '3x3', '3X3', '60' and '10x10' -- three
-- incompatible notations and a bare integer of unstated unit -- and DataSF's
-- published description of the field reads "date tree was planted", copied from
-- PlantDate. Turning that into an area would be D7's forbidden move: dressing an
-- estimate as a measurement. It is shown as the city wrote it, or not at all.
--
-- Not ingested, and each for a reason:
--   SiteOrder                 an ordinal disambiguating several trees at one
--                             address (99.1% populated). It is a key inside the
--                             city's own table, not a fact about the tree, and
--                             "tree 3 of 7" answers nothing anybody asked.
--   XCoord / YCoord           CA State Plane III, the same point as lat/lon.
--   Location                  the string "(lat, lon)". Same point again.
--   Fire Prevention Districts, Police Districts, Supervisor Districts,
--   Zip Codes, Neighborhoods (old), Analysis Neighborhoods
--                             Socrata :@computed_region_* spatial-join
--                             artifacts. Their values are opaque row ids into
--                             other datasets, not names or numbers -- the "Zip
--                             Codes" column's commonest value is 28859. The
--                             seed does its own neighbourhood join against
--                             j2bu-swwd and keeps the name.
--
-- planted_year is section 4's column and stays. planted_on is DataSF's PlantDate
-- kept at its own grain (ISO 'YYYY-MM-DD'), added because the almanac (screen 12)
-- asks "how many trees were planted this spring" and a year cannot answer a
-- question about a season. The two are always set together or both NULL, and
-- planted_year is always planted_on's year -- a pinned invariant rather than a
-- convention, so the cheap column stays usable and the two can never disagree.
CREATE TABLE trees (
    id                 INTEGER PRIMARY KEY,     -- internal join key
    uuid               TEXT NOT NULL UNIQUE,    -- stable citable identity
    external_ref       INTEGER UNIQUE,          -- DataSF TreeID
    source             TEXT NOT NULL,           -- city_import | community
    lat                REAL NOT NULL,
    lon                REAL NOT NULL,
    address            TEXT,
    site_type          TEXT,
    neighborhood_id    INTEGER REFERENCES neighborhoods(id),
    status             TEXT NOT NULL,           -- alive | declining | dead_reported | removed | vacant_site
    species_current    INTEGER REFERENCES species(id),
    planted_year       INTEGER,
    planted_on         TEXT,                    -- ISO date, DataSF PlantDate
    dbh_city_cm_min    INTEGER,
    dbh_city_cm_max    INTEGER,
    site_lineage       INTEGER REFERENCES trees(id),
    verification_state TEXT NOT NULL,           -- unverified | org_verified | city_record
    -- ------------------------------------------------- the city's own record --
    -- Six DataSF columns carried verbatim, for the tree page's "what the city
    -- has on file" panel. All six are FREE TEXT and none carries a CHECK, which
    -- is a decision rather than an omission -- see the block comment below.
    legal_status       TEXT,                    -- DataSF qLegalStatus
    caretaker          TEXT,                    -- DataSF qCaretaker
    care_assistant     TEXT,                    -- DataSF qCareAssistant
    plant_type         TEXT,                    -- DataSF PlantType
    plot_size          TEXT,                    -- DataSF PlotSize, verbatim, never parsed
    permit_notes       TEXT,                    -- DataSF PermitNotes
    city_raw           TEXT,
    created_at         TEXT NOT NULL,
    updated_at         TEXT NOT NULL,
    deleted_at         TEXT,
    CHECK (status IN ('alive','declining','dead_reported','removed','vacant_site')),
    CHECK (verification_state IN ('unverified','org_verified','city_record')),
    CHECK ((dbh_city_cm_min IS NULL) = (dbh_city_cm_max IS NULL)),
    CHECK (city_raw IS NULL OR json_valid(city_raw)),
    -- The two planting columns are one fact at two grains; neither may drift
    -- from the other, and neither may exist without the other.
    CHECK ((planted_on IS NULL) = (planted_year IS NULL)),
    CHECK (planted_on IS NULL OR CAST(substr(planted_on, 1, 4) AS INTEGER) = planted_year)
);

-- Covering index for viewport / nearest queries that do not want the R*Tree.
CREATE INDEX idx_trees_lat_lon ON trees(lat, lon, id);
CREATE INDEX idx_trees_species_current ON trees(species_current);
CREATE INDEX idx_trees_neighborhood ON trees(neighborhood_id);
CREATE INDEX idx_trees_status ON trees(status);
-- The almanac's two neighbourhood-scoped planting reads (screen 12): the elder
-- is a MIN over this within one neighbourhood, and the recent-planting window is
-- a range scan over it. Both are ordered by date inside one neighbourhood, so the
-- index leads on the neighbourhood.
CREATE INDEX idx_trees_neighborhood_planted ON trees(neighborhood_id, planted_on);

-- Spatial index for "trees near a point" and map viewport bbox queries.
-- Keyed directly on trees.id, which is an INTEGER PRIMARY KEY and therefore a
-- rowid alias -- stable across VACUUM, unlike the implicit rowid of a TEXT-PK
-- table. Degenerate (point) rectangles: min == max on both axes.
--
-- IMPORTANT for the GRDB layer: SQLite's rtree module stores coordinates as
-- 32-bit floats and rounds each rectangle OUTWARD. It is therefore a
-- conservative filter -- it never drops a true hit, but it returns a handful of
-- rows just outside the requested box (measured drift here: <= 1.6e-5 deg,
-- about 1.7 m). ALWAYS re-check exactly against trees.lat / trees.lon:
--
--   SELECT t.* FROM trees_rtree r JOIN trees t ON t.id = r.id
--    WHERE r.max_lat >= :minLat AND r.min_lat <= :maxLat
--      AND r.max_lon >= :minLon AND r.min_lon <= :maxLon
--      AND t.lat BETWEEN :minLat AND :maxLat
--      AND t.lon BETWEEN :minLon AND :maxLon;
--
-- For "trees near a point", filter by bbox first, then order by squared
-- distance with a cos(lat) correction on the longitude term.
CREATE VIRTUAL TABLE trees_rtree USING rtree(
    id,               -- == trees.id
    min_lat, max_lat,
    min_lon, max_lon
);

-- ------------------------------------------------------ species_assertions --
-- Append-only. Every non-placeholder city row gets exactly one city_import row.
CREATE TABLE species_assertions (
    id            INTEGER PRIMARY KEY,
    tree_id       INTEGER NOT NULL REFERENCES trees(id),
    species_id    INTEGER NOT NULL REFERENCES species(id),
    source        TEXT NOT NULL,               -- city_import | community | org | ai_suggestion
    confidence    REAL,
    asserted_by   INTEGER,
    superseded_by INTEGER REFERENCES species_assertions(id),
    created_at    TEXT NOT NULL,
    CHECK (source IN ('city_import','community','org','ai_suggestion'))
);
CREATE INDEX idx_assertions_tree ON species_assertions(tree_id);
CREATE INDEX idx_assertions_species ON species_assertions(species_id);

-- ------------------------------------------------------ import provenance --
-- Not part of BUILD-PLAN 4. Mirrors Fixtures/sf_species_map.csv so the weekly
-- diff and Tools/verify_seed.py can audit the mapping without the CSV.
-- species_uuid, not species_id, is the key the checked-in CSV carries: integer
-- ids depend on CSV row order, uuids do not.
CREATE TABLE species_map (
    qspecies_string TEXT PRIMARY KEY,
    species_id      INTEGER REFERENCES species(id),
    species_uuid    TEXT,
    confidence      REAL NOT NULL,
    is_stub         INTEGER NOT NULL,      -- 1 = fell through to the stub path
    is_placeholder  INTEGER NOT NULL,      -- 1 = vacant-site placeholder, no species
    -- 1 = the string names no taxon ("Shrub", "Privet", "To Be Determine").
    -- A tree stands at the site, so it is NOT a placeholder and its status is
    -- `alive`; it simply carries no species. Provenance is a queryable column
    -- rather than a comment (DECISIONS constraint 13).
    is_non_taxon    INTEGER NOT NULL DEFAULT 0,
    tree_count      INTEGER NOT NULL,
    CHECK (species_id IS NULL OR (is_placeholder = 0 AND is_non_taxon = 0))
);

-- Single-row build receipt.
CREATE TABLE seed_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
